###
GET http://localhost:3000/api/product

###
POST http://localhost:3000/api/product
Content-Type: application/json

{
    "product_name":"Hard disk 250GB",
    "product_description":"Unidad de hardware que se usa para almacenar contenido y datos digitales en las computadoras",
    "product_price":250
}

###
PUT http://localhost:3000/api/product/6
Content-Type: application/json

{
    "product_name":"Hard disk 1GB",
    "product_description":"Unidad de hardware que se usa para almacenar contenido y datos digitales en las computadoras",
    "product_price":50
}

###
DELETE http://localhost:3000/api/product/6

###Acceder 
POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "user_name": "Eddy",
    "user_password": "12345"
}

###
GET http://localhost:3000/api/auth